server:
  port: 8080

spring:
  application:
    name: parking

  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        hbm2ddl:
          auto: update

logging:
  file:
   name: C:/Users/bsevi/Desktop/Java-Örneklendirme/Microservice-backend-parking-1/logs/application.log

