server:
  port: 8080

spring:
  application:
    name: parking

  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1234

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
      show-sql: true

logging:
  file:
    name: C:/Users/bsevi/Desktop/Java-Örneklendirme/Microservice-backend-parking-1/logs/application.log
