server:
  port: 8080

spring:
  application:
    name: parking

  datasource:
    url: jdbc:postgresql://localhost:5432/parking
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: postgres

  flyway:
    enabled: true
    baseline-on-migrate: true
    locations: classpath:db/migration

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show-sql: true
        ddl-auto: update

logging:
  file:
   name: C:/Users/log/application.log

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka