-- V1__init_schema.sql

-- Email TABLE
CREATE TABLE emails
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    to_email        VARCHAR(100)                        NOT NULL,
    subject         VARCHAR(100)                        NOT NULL,
    body            VARCHAR(100)                        NOT NULL,
    attachment_path VARCHAR(100),
    send_date       TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);