 V1__init_schema.sql

-- -- Payment Service  TABLE
 CREATE TABLE payments (
                          payment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                           reservation_id BIGINT NOT NULL,
                           amount DECIMAL(10,2) NOT NULL,
                           payment_method VARCHAR(50) NOT NULL,
                      payment_status VARCHAR(20) NOT NULL CHECK (payment_status IN ('PENDING', 'PAID', 'FAILED', 'REFUNDED')),
                         created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
                          updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
 );