server :
  port : 8090

spring:
  application:
    name: reservation-service
  config:
    import: "optional:configserver:http://localhost:8181"
  datasource:
    url: jdbc:postgresql://localhost:5433/reservation
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate.dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka




