-- V1__init_schema.sql

-- USERS TABLE
CREATE TABLE users
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR(255)                            NOT NULL,
    user_name    VARCHAR(255)                            NOT NULL,
    password     VARCHAR(255),
    email        VARCHAR(255),
    phone_number VARCHAR(255),
    active       BOOLEAN,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

-- VEHICLES TABLE
CREATE TABLE vehicles
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    registration_number VARCHAR(255) UNIQUE,
    type                VARCHAR(255),
    is_active           BOOLEAN,
    registration_date   TIMESTAMP WITHOUT TIME ZONE DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT pk_vehicles PRIMARY KEY (id)
);

-- PARKING LOTS TABLE
CREATE TABLE parking_lots
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_parkinglot PRIMARY KEY (id)
);

-- PARKING SPOT TABLE
CREATE TABLE parking_spots
(
    id BIGINT NOT NULL,
    CONSTRAINT pk_parkingspot PRIMARY KEY (id)
);
