server:
  port: 8083

spring:
  application:
    name: email-service

  datasource:
    url: jdbc:postgresql://localhost:5432/email_service
    driver-class-name: org.postgresql.Driver
    username: postgres
    password: 12345

    flyway:
      enabled: true
      baseline-on-migrate: true
      locations: classpath:db/migration

    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQLDialect
          show-sql: true
          ddl-auto: none

  mail:
    host: smtp.gmail.com
    port: 587
    username: test@gmail.com
    password: ruhi123

    properties:
      mail:
        smtp:
          starttls:
            enable: true
            required: true
          auth: true
          connectiontimeout: 5000
          timeout: 5000
          writetimeout: 5000

logging:
  file:
    path: C:\log
  level:
    root: INFO